networks:
  land_net:
    name: fabric_land_net
services:
  ca_gov:
    image: hyperledger/fabric-ca:latest
    container_name: ca_gov
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-gov
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASSWORD=adminpw
    volumes:
      - ../crypto-config/fabric-ca/gov:/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    networks:
      - land_net

  ca_citizen:
    image: hyperledger/fabric-ca:latest
    container_name: ca_citizen
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-citizen
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASSWORD=adminpw
    volumes:
      - ../crypto-config/fabric-ca/citizen:/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:8054"
    networks:
      - land_net